### ISSUE TITLE
Cannot build project

### ISSUE THREAD

**Issue by lhanson** [openwide-java/artifact-listener#46]
Following the instructions in the Readme, I performed the following steps:

- Installed Eclipse Neon
- Start PostgreSQL on port 5432
- Right-click artifact-listener/eclipse/processor all.launch, Run As "processor all" (fails with [output](https://gist.github.com/lhanson/5092ccdaec5f5060369f26736cd2c08d))
- It might be futile given the previous error, but running `MavenArtifactNotifierInitFromExcelMain` fails with [this output](https://gist.github.com/lhanson/13840b989a2cbabd8603ee7754c5fd60)

**Comment by lalmeras** [comment]
For the first error, it is an error of the documentation ; « processor all » does not install artifacts, so when code processing is done in webapp module, core code is not available.

Basic workaround : open run as configuration and modify goals from org.bsc.maven:maven-processor-plugin:process to clean install ; this may process sources for code generation and install artifacts.
MavenArtifactNotifierInitFromExcelMain's error message is too short so that I can't say if it is directly to the first error. Let me know how it works for you and I'll fix README and processor all launch configuration.

**Comment by lalmeras** [comment]
Travis just says me that... I'm wrong. Error is elsewhere. I'll notify when I get some time to work on it.

**Comment by lalmeras** [comment]
I just fix master branch and application can be built and started now. Feel free to notice me here if you encounter another problem.

**Comment by lhanson** [comment]
That helped. However, now when I run the "processor all.launch" file, I get `Variable references non-existent resource : ${workspace_loc:maven-artifact-notifier}`.

If I change the relevant line to:

    <stringAttribute key="org.eclipse.jdt.launching.WORKING_DIRECTORY" value="${workspace_loc:artifact-listener}"/>

it works. This seems to be because the project root directory is named `artifact-listener` by default instead of `maven-artifact-notifier`, no?

**Comment by lhanson** [comment]
Also, running `MavenArtifactNotifierInitFromExcelMain` still [fails](https://gist.github.com/lhanson/13840b989a2cbabd8603ee7754c5fd60) with [this output](https://gist.github.com/lhanson/d9b27542e7b7ac8a7a87885f8123c904) from PostgreSQL.

**Comment by lalmeras** [comment]
The provided logs seems to be an excerpt of PostgreSQL logs ; I think it is normal (application tries to reset tables before initialization) and doesn't allow me to track your problem. Can you provide output from MavenArtifactNotifierInitFromExcelMain stdout (Eclipse's console view content) ?

**Comment by lhanson** [comment]
Here's the [output from MavenArtifactNotifierInitFromExcelMain](https://gist.github.com/lhanson/13840b989a2cbabd8603ee7754c5fd60).

**Comment by lalmeras** [comment]
Can you check that If you cannot connect with the following command (I think that database connection is the problem) :
```
psql -U maven_artifact_notifier -h localhost -W
```

If you can't, set user's password with (as postgres or maven_artifact_notifier user):
```
alter user maven_artifact_notifier with password 'maven_artifact_notifier';
```

If connection is stil broken, please check your pg_hba.conf (postgresql configuration) and postgresql.conf to ensure that localhost connection with password is enabled.

**Comment by lhanson** [comment]
My local postgres instance is up and reachable:
```
psql -U maven_artifact_notifier -h localhost -W
Password for user maven_artifact_notifier:
psql (9.5.4)
Type "help" for help.
```

Oddly, I notice that there are some tables created after I run `MavenArtifactNotifierInitFromExcelMain` even though it reports failure, so maybe some of it completes successfully?

```
maven_artifact_notifier=# \d
                                List of relations
 Schema |                Name                |   Type   |          Owner
--------+------------------------------------+----------+-------------------------
 public | artifact                           | table    | maven_artifact_notifier
 public | artifact_id_seq                    | sequence | maven_artifact_notifier
 public | artifactgroup                      | table    | maven_artifact_notifier
 public | artifactgroup_id_seq               | sequence | maven_artifact_notifier
 public | artifactnotificationrule           | table    | maven_artifact_notifier
 public | artifactnotificationrule_id_seq    | sequence | maven_artifact_notifier
 public | artifactversion                    | table    | maven_artifact_notifier
 public | artifactversion_id_seq             | sequence | maven_artifact_notifier
 public | artifactversionnotification        | table    | maven_artifact_notifier
 public | artifactversionnotification_id_seq | sequence | maven_artifact_notifier
 public | authority                          | table    | maven_artifact_notifier
 public | authority_custompermissionnames    | table    | maven_artifact_notifier
 public | authority_id_seq                   | sequence | maven_artifact_notifier
 public | emailaddress                       | table    | maven_artifact_notifier
 public | emailaddress_id_seq                | sequence | maven_artifact_notifier
 public | externallinkwrapper                | table    | maven_artifact_notifier
 public | externallinkwrapper_id_seq         | sequence | maven_artifact_notifier
 public | followedartifact                   | table    | maven_artifact_notifier
 public | followedartifact_id_seq            | sequence | maven_artifact_notifier
 public | parameter                          | table    | maven_artifact_notifier
 public | parameter_id_seq                   | sequence | maven_artifact_notifier
 public | project                            | table    | maven_artifact_notifier
 public | project_id_seq                     | sequence | maven_artifact_notifier
 public | project_projectlicense             | table    | maven_artifact_notifier
 public | projectlicense                     | table    | maven_artifact_notifier
 public | projectlicense_id_seq              | sequence | maven_artifact_notifier
 public | projectversion                     | table    | maven_artifact_notifier
 public | projectversion_id_seq              | sequence | maven_artifact_notifier
 public | queuedtaskholder                   | table    | maven_artifact_notifier
 public | queuedtaskholder_id_seq            | sequence | maven_artifact_notifier
 public | statistic                          | table    | maven_artifact_notifier
 public | statistic_id_seq                   | sequence | maven_artifact_notifier
 public | user_                              | table    | maven_artifact_notifier
 public | user__authority                    | table    | maven_artifact_notifier
 public | user__id_seq                       | sequence | maven_artifact_notifier
 public | user__usergroup                    | table    | maven_artifact_notifier
 public | usergroup                          | table    | maven_artifact_notifier
 public | usergroup_authority                | table    | maven_artifact_notifier
 public | usergroup_id_seq                   | sequence | maven_artifact_notifier
(39 rows)

maven_artifact_notifier=#
```

**Comment by lalmeras** [comment]
Can you update code to retrieve this commit a766795fadd002175a46961fcba8430e09d19782 on master so that initialization failure give us more information ?

**Comment by lhanson** [comment]
Thanks, here's the additional exception information.
```
[2016-10-23 17:16:03,595] WARN  - pertyPlaceholderConfigurer -  - Could not load properties from URL [file:/etc/maven-artifact-notifier/configuration.properties]: /etc/maven-artifact-notifier/configuration.properties (No such file or directory)
[2016-10-23 17:16:03,597] WARN  - pertyPlaceholderConfigurer -  - Could not load properties from class path resource [configuration-ldhanson2.properties]: class path resource [configuration-ldhanson2.properties] cannot be opened because it does not exist
[2016-10-23 17:16:05,498] WARN  - bernatePersistenceProvider -  - Installing our Spring managed interceptor.
[2016-10-23 17:16:05,893] WARN  - stractEhcacheRegionFactory -  - HHH020003: Could not find a specific ehcache configuration for cache named [fr.openwide.core.jpa.externallinkchecker.business.model.ExternalLinkWrapper]; using defaults.
[2016-10-23 17:16:05,917] WARN  - stractEhcacheRegionFactory -  - HHH020003: Could not find a specific ehcache configuration for cache named [fr.openwide.maven.artifact.notifier.core.business.project.model.Project]; using defaults.
[2016-10-23 17:16:05,952] WARN  - stractEhcacheRegionFactory -  - HHH020003: Could not find a specific ehcache configuration for cache named [fr.openwide.maven.artifact.notifier.core.business.project.model.ProjectVersion]; using defaults.
[2016-10-23 17:16:05,976] WARN  - stractEhcacheRegionFactory -  - HHH020003: Could not find a specific ehcache configuration for cache named [fr.openwide.maven.artifact.notifier.core.business.user.model.UserGroup.authorities]; using defaults.
[2016-10-23 17:16:06,006] WARN  - stractEhcacheRegionFactory -  - HHH020003: Could not find a specific ehcache configuration for cache named [fr.openwide.maven.artifact.notifier.core.business.project.model.Project.versions]; using defaults.
[2016-10-23 17:16:09,620] WARN  - onConfigApplicationContext -  - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class fr.openwide.maven.artifact.notifier.core.config.spring.MavenArtifactNotifierCoreCommonJpaConfig: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory
[2016-10-23 17:16:09,635] ERROR - tNotifierInitFromExcelMain -  - Initialization fails
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class fr.openwide.maven.artifact.notifier.core.config.spring.MavenArtifactNotifierCoreCommonJpaConfig: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1054)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:829)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
	at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:84)
	at fr.openwide.maven.artifact.notifier.init.MavenArtifactNotifierInitFromExcelMain.main(MavenArtifactNotifierInitFromExcelMain.java:23)
Caused by: javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.persistenceException(EntityManagerFactoryBuilderImpl.java:954)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:884)
	at org.hibernate.jpa.HibernatePersistenceProvider.createContainerEntityManagerFactory(HibernatePersistenceProvider.java:135)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:343)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:319)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
	... 11 more
Caused by: org.hibernate.search.exception.SearchException: HSEARCH000103: Unable to initialize IndexManager named 'fr.openwide.maven.artifact.notifier.core.business.user.model.UserGroup'
	at org.hibernate.search.indexes.impl.IndexManagerHolder.createIndexManager(IndexManagerHolder.java:260)
	at org.hibernate.search.indexes.impl.IndexManagerHolder.createIndexManager(IndexManagerHolder.java:513)
	at org.hibernate.search.indexes.impl.IndexManagerHolder.createIndexManagers(IndexManagerHolder.java:482)
	at org.hibernate.search.indexes.impl.IndexManagerHolder.buildEntityIndexBinding(IndexManagerHolder.java:91)
	at org.hibernate.search.spi.SearchIntegratorBuilder.initDocumentBuilders(SearchIntegratorBuilder.java:358)
	at org.hibernate.search.spi.SearchIntegratorBuilder.buildNewSearchFactory(SearchIntegratorBuilder.java:199)
	at org.hibernate.search.spi.SearchIntegratorBuilder.buildSearchIntegrator(SearchIntegratorBuilder.java:117)
	at org.hibernate.search.hcore.impl.HibernateSearchSessionFactoryObserver.sessionFactoryCreated(HibernateSearchSessionFactoryObserver.java:75)
	at org.hibernate.internal.SessionFactoryObserverChain.sessionFactoryCreated(SessionFactoryObserverChain.java:35)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:520)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:465)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:881)
	... 16 more
Caused by: org.hibernate.search.exception.SearchException: HSEARCH000252: Unable to initialize directory provider org.hibernate.search.store.impl.FSDirectoryProvider for index fr.openwide.maven.artifact.notifier.core.business.user.model.UserGroup
	at org.hibernate.search.store.spi.BaseDirectoryProviderService.initialize(BaseDirectoryProviderService.java:67)
	at org.hibernate.search.store.spi.BaseDirectoryProviderService.create(BaseDirectoryProviderService.java:52)
	at org.hibernate.search.indexes.spi.DirectoryBasedIndexManager.createDirectoryProvider(DirectoryBasedIndexManager.java:230)
	at org.hibernate.search.indexes.spi.DirectoryBasedIndexManager.initialize(DirectoryBasedIndexManager.java:90)
	at org.hibernate.search.indexes.impl.IndexManagerHolder.createIndexManager(IndexManagerHolder.java:256)
	... 27 more
Caused by: org.hibernate.search.exception.SearchException: Unable to create index directory: /data/services/maven-artifact-notifier/lucene for index fr.openwide.maven.artifact.notifier.core.business.user.model.UserGroup
	at org.hibernate.search.store.impl.DirectoryProviderHelper.makeSanityCheckedDirectory(DirectoryProviderHelper.java:155)
	at org.hibernate.search.store.spi.DirectoryHelper.getVerifiedIndexPath(DirectoryHelper.java:88)
	at org.hibernate.search.store.spi.DirectoryHelper.getVerifiedIndexDir(DirectoryHelper.java:104)
	at org.hibernate.search.store.impl.FSDirectoryProvider.initialize(FSDirectoryProvider.java:49)
	at org.hibernate.search.store.spi.BaseDirectoryProviderService.initialize(BaseDirectoryProviderService.java:64)
	... 31 more
```

**Comment by lalmeras** [comment]
Please create a folder named /data/services/maven-artifact-notifier/ or provides a different configuration for data.path property in configuration.properties ; I update README.md to provides this information.

Folder is used to store lucene indexes, used for plain text search.

**Comment by lhanson** [comment]
Progress! Okay, folder created and we get past that error. Now it looks like there are some [compilation problems](https://gist.github.com/lhanson/518233467f4ebef84db51153507faea5).

**Comment by lalmeras** [comment]
Either artifact-listener/eclipse/processor all.launch fails (I don't think this is the problem) or maven eclipse integration fails to add generated sources to project.

Can you check that target/generated-sources/apt is added as a source folder on maven-artifact-notifier-core ? If not, can you add the folder manually and retry ?

**Comment by lhanson** [comment]
Fantastic, I've added `target/generated-sources/apt` to the project build path and now `MavenArtifactNotifierInitFromExcelMain ` completes successfully. Thanks for your help getting me up and running!

**Comment by lalmeras** [comment]
Thanks for all your feedbacks.
